# Generated by Django 4.2 on 2024-04-22 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('is_active', models.BooleanField(default=False, verbose_name='Is Active')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='Updated Date')),
                ('first_name', models.CharField(max_length=255, verbose_name='First Name')),
                ('last_name', models.CharField(max_length=255, verbose_name='Last Name')),
                ('sex', models.CharField(max_length=8, verbose_name='Sex')),
                ('birth_day', models.DateField(verbose_name='Birth Day')),
                ('national_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='National Code')),
                ('file_number', models.CharField(max_length=100, verbose_name='File Number')),
            ],
            options={
                'verbose_name': 'Patient',
                'verbose_name_plural': 'Patients',
            },
        ),
    ]
