# Generated by Django 4.2 on 2024-06-24 16:09

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر داده شده')),
                ('available_time', models.DateTimeField(verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'نوبت آزاد',
                'verbose_name_plural': 'نوبت های آزاد',
            },
        ),
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر داده شده')),
                ('first_name', models.CharField(max_length=255, verbose_name='نام')),
                ('last_name', models.CharField(max_length=255, verbose_name='نام خانوادگی')),
                ('password', models.CharField(max_length=20, verbose_name='رمز عبور')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('national_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='کد ملی')),
            ],
            options={
                'verbose_name': 'پزشک',
                'verbose_name_plural': 'پزشک ها',
            },
        ),
        migrations.CreateModel(
            name='DoctorsServices',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر داده شده')),
                ('doctor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.doctor', verbose_name='پزشک')),
            ],
            options={
                'verbose_name': 'خدمت پزشک',
                'verbose_name_plural': 'خدمات پزشک',
            },
        ),
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر داده شده')),
                ('medicine_name', models.CharField(max_length=255, verbose_name='نام دارو')),
            ],
            options={
                'verbose_name': 'دارو',
                'verbose_name_plural': 'داروها',
            },
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر داده شده')),
                ('username', models.CharField(max_length=255, unique=True, verbose_name='نام کاربری')),
                ('password', models.CharField(max_length=20, verbose_name='رمز عبور')),
                ('first_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='نام')),
                ('last_name', models.CharField(blank=True, default=None, max_length=255, null=True, verbose_name='نام خانوادگی')),
                ('phone_number', models.CharField(blank=True, default=None, max_length=11, null=True, verbose_name='شماره تماس')),
                ('sex', models.CharField(choices=[('مرد', 'مرد'), ('زن', 'زن')], default=None, max_length=9, null=True, verbose_name='جنسیت')),
                ('birth_day', models.DateField(blank=True, default=None, null=True, verbose_name='تاریخ تولد')),
                ('file_number', models.IntegerField(blank=True, default=None, null=True, verbose_name='شماره پرونده')),
            ],
            options={
                'verbose_name': 'مراجعه کننده',
                'verbose_name_plural': 'مراجعین',
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر داده شده')),
                ('title', models.CharField(max_length=255, verbose_name='تشخیص')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'گزارش',
                'verbose_name_plural': 'گزارشات',
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر داده شده')),
                ('title', models.CharField(max_length=255, verbose_name='موضوع')),
                ('cost', models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='هزینه')),
            ],
            options={
                'verbose_name': 'سرویس',
                'verbose_name_plural': 'سرویس ها',
            },
        ),
        migrations.CreateModel(
            name='UsersSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر داده شده')),
                ('title', models.CharField(max_length=255, verbose_name='موضوع')),
                ('type', models.CharField(choices=[('پیشنهاد', 'پیشنهاد'), ('انتقاد', 'انتقاد')], default='پیشنهاد', max_length=9, verbose_name='نوع')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'پیشنهاد و انتقاد',
                'verbose_name_plural': 'پیشنهادات و انتقادات',
            },
        ),
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر داده شده')),
                ('date', models.DateTimeField(verbose_name='تاریخ')),
                ('doctor_and_service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.doctorsservices', verbose_name='خدمات و پزشک')),
            ],
            options={
                'verbose_name': 'نوبت',
                'verbose_name_plural': 'نوبت ها',
            },
        ),
        migrations.CreateModel(
            name='PatientsReports',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر داده شده')),
                ('medicine_count', models.IntegerField(verbose_name='تعداد مورد نیاز')),
                ('medicine_description', models.TextField(verbose_name='طریقه مصرف')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.medicine', verbose_name='دارو')),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.patient', verbose_name='مراجعه کننده')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.report', verbose_name='گزارش')),
            ],
            options={
                'verbose_name': 'گزارش مراجعه کننده',
                'verbose_name_plural': 'گزارشات مراجعه کننده',
            },
        ),
        migrations.AddField(
            model_name='patient',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.reservation', verbose_name='نوبت'),
        ),
        migrations.AddField(
            model_name='doctorsservices',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='patient.service', verbose_name='خدمت'),
        ),
    ]
