# Generated by Django 4.2 on 2024-04-24 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0002_report_alter_patient_options_alter_patient_birth_day_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر داده شده')),
                ('medicine_name', models.CharField(max_length=255, verbose_name='نام دارو')),
                ('medicine_count', models.IntegerField(verbose_name='تعداد مورد نیاز')),
                ('medicine_description', models.TextField(verbose_name='طریقه مصرف')),
            ],
            options={
                'verbose_name': 'دارو',
                'verbose_name_plural': 'داروها',
            },
        ),
        migrations.AlterField(
            model_name='report',
            name='title',
            field=models.CharField(max_length=255, verbose_name='تشخیص'),
        ),
    ]
