# Generated by Django 4.2 on 2024-04-24 11:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0003_medicine_alter_report_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='patientsreports',
            name='medicine',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='patient.medicine', verbose_name='دارو'),
            preserve_default=False,
        ),
    ]
