# Generated by Django 4.2 on 2024-05-02 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0006_service_reservation_patient_reservation'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='reservation',
            options={'verbose_name': 'نوبت', 'verbose_name_plural': 'نوبت ها'},
        ),
        migrations.AlterField(
            model_name='patient',
            name='file_number',
            field=models.CharField(max_length=100, unique=True, verbose_name='شماره پرونده'),
        ),
        migrations.AlterField(
            model_name='reservation',
            name='date',
            field=models.DateTimeField(verbose_name='تاریخ'),
        ),
    ]
