# Generated by Django 4.2 on 2024-05-02 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0007_alter_reservation_options_alter_patient_file_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='patient',
            name='total_paid',
            field=models.FloatField(default=0, verbose_name='هزینه پرداخت شده'),
        ),
    ]
