# Generated by Django 4.2 on 2024-05-02 20:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0008_patient_total_paid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='patient',
            name='total_paid',
        ),
        migrations.AlterField(
            model_name='patient',
            name='file_number',
            field=models.IntegerField(unique=True, verbose_name='شماره پرونده'),
        ),
        migrations.AlterField(
            model_name='service',
            name='cost',
            field=models.FloatField(validators=[django.core.validators.MinValueValidator(1)], verbose_name='هزینه'),
        ),
    ]
