# Generated by Django 4.2 on 2024-05-30 12:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0010_account_patient_phone_number'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableTimes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر داده شده')),
                ('available_time', models.DateTimeField(verbose_name='تاریخ')),
            ],
            options={
                'verbose_name': 'نوبت آزاد',
                'verbose_name_plural': 'نوبت های آزاد',
            },
        ),
        migrations.CreateModel(
            name='UsersSuggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر داده شده')),
                ('title', models.CharField(max_length=255, verbose_name='موضوع')),
                ('type', models.CharField(choices=[('پیشنهاد', 'پیشنهاد'), ('انتقاد', 'انتقاد')], default='پیشنهاد', max_length=9, verbose_name='نوع')),
                ('description', models.TextField(verbose_name='توضیحات')),
            ],
            options={
                'verbose_name': 'پیشنهاد و انتقاد',
                'verbose_name_plural': 'پیشنهادات و انتقادات',
            },
        ),
    ]
