# Generated by Django 4.2 on 2024-05-30 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0011_availabletimes_userssuggestion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patient',
            name='reservation',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.reservation', verbose_name='نوبت'),
        ),
    ]
