# Generated by Django 4.2 on 2024-06-11 13:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0012_alter_patient_reservation'),
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('is_active', models.BooleanField(default=False, verbose_name='فعال')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='تاریخ ایجاد شده')),
                ('updated_date', models.DateTimeField(auto_now=True, verbose_name='تاریخ تغییر داده شده')),
                ('first_name', models.CharField(max_length=255, verbose_name='نام')),
                ('last_name', models.CharField(max_length=255, verbose_name='نام خانوادگی')),
                ('password', models.CharField(max_length=20, verbose_name='رمز عبور')),
                ('phone_number', models.CharField(max_length=11, verbose_name='شماره تماس')),
                ('national_code', models.CharField(max_length=10, primary_key=True, serialize=False, verbose_name='کد ملی')),
            ],
            options={
                'verbose_name': 'پزشک',
                'verbose_name_plural': 'پزشک ها',
            },
        ),
        migrations.AlterField(
            model_name='patient',
            name='reservation',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='patient.reservation', verbose_name='نوبت'),
        ),
    ]
