# Generated by Django 4.2 on 2024-06-23 14:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('patient', '0014_remove_reservation_service_doctorsservices_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='account',
            old_name='first_name',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='account',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='account',
            name='phone_number',
        ),
    ]
